# 5교시 3.자연어 처리
- 언어의 규칙을 컴퓨터가 이해하기엔 너무 어려웠다.
- 딥러닝을 통해 단어를 2차원 평면에서 거대한 벡터공간에 좌표시키는 것이 가능. 단어 사이의 관계 파악이 가능했음.
- 확장하면, 단어 간의 확률을 하나의 벡터공간에 저장해놓은것이 언어모델이고, 챗지피티 같은 게 있음. 또 크게는 모든 언어에 대해서도 확장.
- 토큰화, 임베딩
- 토큰화: 커피, 한, 잔, 따로 -> 어디에서 끊어야 하는가
- 임베딩: 각 단어를 어느 수치를 주어야 벡터공간에서 적절한가? (신경망 이용)
- 모든 관계의 그룹, 관계를 알고 수정할 수 있게 됨

- 토큰화 과정에서 Sequence로 만들어주어야 추후 패딩이 가능.
- texts_to_sequences로 텍스트를 시퀀스로 변환
sequences = tokenizer.texts_to_sequences(texts)
- 각기 다른 문장의 길이를 동일하게 맞추어 임베딩 하기 위해 패딩을 진행 (길이가 같아야 수정/변환이 가능하므로)

## 1. 텍스트의 토큰화

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import numpy as np

# 전처리할 텍스트를 정합니다.
text = '커피 한잔 어때'

# Tokenizer 객체 생성 및 fit_on_texts로 단어 인덱스 학습
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

# texts_to_sequences로 텍스트를 시퀀스로 변환
sequences = tokenizer.texts_to_sequences([text])

# 단어 인덱스 확인
word_index = tokenizer.word_index
print("\n단어 인덱스:\n", word_index)



단어 인덱스:
 {'커피': 1, '한잔': 2, '어때': 3}


In [ ]:
# 단어 빈도수 세기

# 전처리하려는 세 개의 문장을 정합니다.
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',
       ]

# 토큰화 함수를 이용해 전처리 하는 과정입니다.
tokenizer = Tokenizer()            # 토큰화 함수 지정
tokenizer.fit_on_texts(docs)       # 토큰화 함수에 문장 적용

# 단어의 빈도수를 계산한 결과를 각 옵션에 맞추어 출력합니다.
print("\n단어 카운트:\n", token.word_counts)

# 출력되는 순서는 랜덤입니다.
print("\n문장 카운트: ", token.document_count)
print("\n각 단어가 몇 개의 문장에 포함되어 있는가:\n", token.word_docs)
print("\n각 단어에 매겨진 인덱스 값:\n",  token.word_index)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트:  3

각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'단어를': 1, '토큰화합니다': 1, '텍스트의': 2, '각': 1, '먼저': 1, '나누어': 1, '단어로': 1, '토큰화해야': 1, '인식됩니다': 1, '딥러닝에서': 2, '있습니다': 1, '결과는': 1, '수': 1, '토큰화한': 1, '사용할': 1})

각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


In [4]:
# 전처리할 텍스트를 정합니다.
texts =  ['내일 떡볶이 먹으러 가자', '떡볶이는 참 맛있어', '요즘 더워서 입맛이 없다']

# Tokenizer 객체 생성 및 fit_on_texts로 단어 인덱스 학습
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

# texts_to_sequences로 텍스트를 시퀀스로 변환
sequences = tokenizer.texts_to_sequences(texts)

# 단어 인덱스 확인
word_index = tokenizer.word_index
print("\n단어 인덱스:\n", word_index)

##### 패딩을 통해 시퀀스 길이를 맞춥니다.
print("\n시퀀스:\n", sequences)
padded_sequences = pad_sequences(sequences, 4)
print("\n패딩된 시퀀스:\n", padded_sequences)

model = Sequential()
model.add(Embedding(input_dim=len(word_index) + 1, output_dim=5, input_length=4))
#input_dim에 1을 더하는 것은 인덱스 0을 패딩 값으로 사용하기 위함.
#Keras의 Tokenizer는 단어 인덱스를 1부터 시작하기 때문에, 인덱스 0은 패딩 값으로 예약
#output_dim은 단어가 임베딩될 벡터의 길이

# 임베딩 결과 확인
embedding_output = model.predict(padded_sequences)
print("\n임베딩 결과:\n", embedding_output)



단어 인덱스:
 {'내일': 1, '떡볶이': 2, '먹으러': 3, '가자': 4, '떡볶이는': 5, '참': 6, '맛있어': 7, '요즘': 8, '더워서': 9, '입맛이': 10, '없다': 11}

시퀀스:
 [[1, 2, 3, 4], [5, 6, 7], [8, 9, 10, 11]]

패딩된 시퀀스:
 [[ 1  2  3  4]
 [ 0  5  6  7]
 [ 8  9 10 11]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step

임베딩 결과:
 [[[ 0.02806461  0.01764183 -0.03729599 -0.03247909  0.00428285]
  [-0.04824338  0.00273188  0.00874938 -0.02217491 -0.04502351]
  [ 0.03482396 -0.02569324 -0.02845721  0.01500436  0.01807901]
  [-0.01886079  0.01083529  0.01428589 -0.03871486 -0.04510821]]

 [[-0.03127792 -0.02976793 -0.0138091   0.03903208 -0.03142831]
  [ 0.03491836  0.03119615  0.03707058 -0.02153922  0.00623661]
  [-0.033401   -0.0337594   0.02087737  0.04334459 -0.02020617]
  [ 0.029542   -0.03242177 -0.04751403  0.04594194  0.04026134]]

 [[ 0.04873325  0.03426032 -0.03514082  0.03783559  0.02488995]
  [-0.04748409 -0.04569974 -0.02566934  0.02626978 -0.02907143]
  [ 0.00656276 -0.00147523  0.04705269  0.02988234 -0.04544923]
  [-0.02258239  0.0